name: scratcher
description: Scratch card widget which temporarily hides content from user.
version: 1.3.0
homepage: https://github.com/vintage/scratcher
authors:
  - Kamil Rykowski <kamil.rykowski@gmail.com>

environment:
  sdk: ">=2.2.0 <3.0.0"
  flutter: ">=1.12.1"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.7.0
  flutter_test:
    sdk: flutter
