name: scratcher
description: Scratch card widget which temporarily hides content from the user.
homepage: https://github.com/vintage/scratcher

version: 2.2.1

environment:
  sdk: ">=2.13.0 <4.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lint:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - icons/eye_hide_cloud.png
    - assets/images/eye_hide_cloud.png
